export default {
    products: [
        {
            id: '1',
            name: 'Product name 01',
            description_small: 'Product description small 01',
            description_big: 'Product description big 01',
            image: '/img/products/product-1.jpg',
            price: 10,
            brand: 'Brand01',
            features: ['feature1a', 'feature1b', 'feature1c', ],
            rating: 1,
            reviews: 1,
            stock: 11,
            discount: 10,
        },
        {
            id: '2',
            name: 'Product name 02',
            description_small: 'Product description small 02',
            description_big: 'Product description big 02',
            image: '/img/products/product-2.jpg',
            price: 20,
            brand: 'Brand02',
            features: ['feature2a', 'feature2b', 'feature2c', ],
            rating: 1.5,
            reviews: 2,
            stock: 12,
            discount: 0,
        },
        {
            id: '3',
            name: 'Product name 03',
            description_small: 'Product description small 03',
            description_big: 'Product description big 03',
            image: '/img/products/product-3.jpg',
            price: 30,
            brand: 'Brand03',
            features: ['feature3a', 'feature3b', 'feature3c', ],
            rating: 2,
            reviews: 3,
            stock: 13,
            discount: 10,
        },
        {
            id: '4',
            name: 'Product name 04',
            description_small: 'Product description small 04',
            description_big: 'Product description big 04',
            image: '/img/products/product-4.jpg',
            price: 40,
            brand: 'Brand04',
            features: ['feature4a', 'feature4b', 'feature4c', ],
            rating: 2.5,
            reviews: 4,
            stock: 14,
            discount: 0,
        },
        {
            id: '5',
            name: 'Product name 05',
            description_small: 'Product description small 05',
            description_big: 'Product description big 05',
            image: '/img/products/product-5.jpg',
            price: 50,
            brand: 'Brand05',
            features: ['feature5a', 'feature5b', 'feature5c', ],
            rating: 3,
            reviews: 5,
            stock: 15,
            discount: 10,
        },
        {
            id: '6',
            name: 'Product name 06',
            description_small: 'Product description small 06',
            description_big: 'Product description big 06',
            image: '/img/products/product-6.jpg',
            price: 60,
            brand: 'Brand06',
            features: ['feature6a', 'feature6b', 'feature6c', ],
            rating: 3.5,
            reviews: 6,
            stock: 16,
            discount: 0,
        }
    ],
}